<?php

define('SensorKesselSollTemp', 1);
define('SensorKesselIstTemp', 2);
define('SensorWarmwasserSollTemp', 3);
define('SensorWarmwasserIstTemp', 4);
define('SensorVorlaufHK1SollTemp', 5);
define('SensorVorlaufHK1IstTemp', 6);
define('SensorVorlaufHK2SollTemp', 7);
define('SensorVorlaufHK2IstTemp', 8);
define('SensorMischersteuerung', 9);
define('SensorRuecklaufTemp', 10);
define('SensorAussenTemp', 11);
define('SensorGedaempfteAussenTemp', 12);
define('SensorRaumSollTemp', 13);
define('SensorRaumIstTemp', 14);
define('SensorMomLeistung', 15);
define('SensorMaxLeistung', 16);
define('SensorFlammenstrom', 17);
define('SensorSystemdruck', 18);
define('SensorBetriebszeit', 19);
define('SensorBrennerstarts', 20);
define('SensorWarmwasserbereitungsZeit', 21);
define('SensorWarmwasserBereitungen', 22);
define('SensorFlamme', 100);
define('SensorBrenner', 101);
define('SensorZuendung', 102);
define('SensorHKPumpe', 103);
define('SensorHK1Active', 104);
define('SensorHK2Active', 105);
define('SensorHKWW', 106);
define('SensorZirkulation', 107);
define('Sensor3WegeHeizen', 108);
define('Sensor3WegeWW', 109);
define('SensorWarmwasserBereitung', 110);
define('SensorAutomatikbetrieb', 111);
define('SensorTagbetrieb', 112);
define('SensorSommerbetrieb', 113);
define('SensorWarmwasserTempOK', 114);

define('ReadingTypeNone', 0);
define('ReadingTypeTemperature', 1);
define('ReadingTypePercent', 2);
define('ReadingTypeCurrent', 3);
define('ReadingTypePressure', 4);
define('ReadingTypeTime', 5);
define('ReadingTypeCount', 6);
?>
